version: '3.7'

services:
  db:
    image: postgres
    environment:
     - POSTGRES_DB=hotel
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=user0807
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /hotel/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/hotel
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
