# Generated by Django 3.0.5 on 2020-04-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='start_time',
        ),
    ]
